overwrite: true
schema: "https://builder.open-decision.org/graphql"
documents:
  - src/features/Data/queries.graphql
  - src/features/Data/mutations.graphql
generates:
  src/types/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-query"
    config:
      fetcher: graphql-request
  src/types/generated/graphql.schema.json:
    plugins:
      - "introspection"
