overwrite: true
schema: "https://builder.open-decision.org/graphql"
documents:
  - src/features/Data/queries.graphql
  - src/features/Data/mutations.graphql
generates:
  src/types/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-urql"
    config:
      withHooks: true
  src/types/generated/graphql.schema.json:
    plugins:
      - "introspection"
