schema: "./src/types/generated/graphql.schema.json"
documents:
  - src/features/Data/queries.graphql
  - src/features/Data/mutations.graphql
extensions:
  endpoints:
    default:
      url: "https://builder.open-decision.org/graphql"
